# Generated by Django 3.1.1 on 2020-11-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201127_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myevents',
            old_name='event',
            new_name='u_event',
        ),
    ]
