# Generated by Django 3.1.1 on 2020-11-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201125_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='register_file',
            field=models.FileField(blank=True, upload_to='List'),
        ),
    ]
