# Generated by Django 3.1.1 on 2020-11-27 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201126_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='etime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
